@ProductManagmentAPI_HostAddress = http://localhost:5226

POST {{ProductManagmentAPI_HostAddress}}/api/product/AddProduct
Accept: application/json
Content-Type: application/json

{
  "name": "fsdfdsfds wrong Apples",
  "productGroupId": 2,
  "price": 200,
  "vat": 10,
  "storeIds": [1, 2]
}

###

GET {{ProductManagmentAPI_HostAddress}}/api/product/2
Accept: application/json
Content-Type: application/json

###

GET {{ProductManagmentAPI_HostAddress}}/api/product/GetProductGroupTree
Accept: application/json
Content-Type: application/json


